/**
 * ODE Core Component Library — Code-level Design System
 * Generated by: Figma (visual) → Claude Code (production code)
 *
 * Stack: React + Tailwind CSS + class-variance-authority (cva)
 * No design handoff. Designer defines in Figma, Claude Code outputs this.
 */

import { cva, type VariantProps } from "class-variance-authority";
import { type ReactNode, type ButtonHTMLAttributes, type InputHTMLAttributes } from "react";

// ── Utility ─────────────────────────────────────────────────────────────────

function cn(...classes: (string | undefined | false)[]) {
  return classes.filter(Boolean).join(" ");
}

// ── Button ───────────────────────────────────────────────────────────────────

const buttonVariants = cva(
  // Base: Apple-style — no border, crisp corners, SF Pro weight
  [
    "inline-flex items-center justify-center gap-2",
    "font-sans font-medium rounded-md",
    "transition-all duration-fast ease-out",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-border-focus focus-visible:ring-offset-2",
    "disabled:pointer-events-none disabled:opacity-40",
    "select-none",
  ].join(" "),
  {
    variants: {
      variant: {
        primary: [
          "bg-brand-accent text-white",
          "hover:bg-brand-accent-hover active:bg-brand-accent-pressed",
        ].join(" "),
        secondary: [
          "bg-surface-secondary text-text-primary border border-border-default",
          "hover:bg-surface-tertiary active:bg-surface-tertiary",
        ].join(" "),
        ghost: [
          "bg-transparent text-text-secondary",
          "hover:bg-surface-secondary hover:text-text-primary",
        ].join(" "),
        danger: [
          "bg-error text-white",
          "hover:bg-red-500 active:bg-red-600",
        ].join(" "),
        // Apple-style filled dark button (used on light marketing pages)
        dark: [
          "bg-brand-midnight text-white",
          "hover:bg-opacity-90 active:bg-opacity-80",
        ].join(" "),
      },
      size: {
        sm: "h-7 px-3 text-sm rounded-md",
        md: "h-9 px-4 text-base rounded-lg",
        lg: "h-11 px-6 text-lg rounded-xl",
      },
    },
    defaultVariants: {
      variant: "primary",
      size:    "md",
    },
  }
);

interface ButtonProps
  extends ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  loading?: boolean;
}

export function Button({ variant, size, loading, className, children, disabled, ...props }: ButtonProps) {
  return (
    <button
      className={cn(buttonVariants({ variant, size }), className)}
      disabled={disabled || loading}
      {...props}
    >
      {loading && (
        <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
      )}
      {children}
    </button>
  );
}

// ── Input ────────────────────────────────────────────────────────────────────

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  hint?: string;
  error?: string;
  suffix?: string;   // e.g. "kg", "m/s²"
  prefix?: ReactNode;
}

export function Input({ label, hint, error, suffix, prefix, className, id, ...props }: InputProps) {
  const inputId = id ?? label?.toLowerCase().replace(/\s+/g, "-");
  return (
    <div className="flex flex-col gap-1.5">
      {label && (
        <label
          htmlFor={inputId}
          className="text-sm font-medium text-text-primary"
        >
          {label}
        </label>
      )}
      <div className="relative flex items-center">
        {prefix && (
          <span className="absolute left-3 text-text-tertiary">{prefix}</span>
        )}
        <input
          id={inputId}
          className={cn(
            "w-full h-9 rounded-lg border bg-surface-primary px-3 text-base text-text-primary",
            "placeholder:text-text-tertiary",
            "transition-colors duration-fast",
            "focus:outline-none focus:border-border-focus focus:ring-1 focus:ring-border-focus",
            error
              ? "border-error focus:border-error focus:ring-error"
              : "border-border-default hover:border-border-strong",
            prefix && "pl-9",
            suffix && "pr-14",
            className
          )}
          {...props}
        />
        {suffix && (
          <span className="absolute right-3 text-sm text-text-tertiary font-mono">
            {suffix}
          </span>
        )}
      </div>
      {error ? (
        <p className="text-sm text-error">{error}</p>
      ) : hint ? (
        <p className="text-sm text-text-tertiary">{hint}</p>
      ) : null}
    </div>
  );
}

// ── Card ─────────────────────────────────────────────────────────────────────

const cardVariants = cva(
  "rounded-xl bg-surface-secondary transition-shadow duration-fast",
  {
    variants: {
      variant: {
        default:  "border border-border-default shadow-xs",
        elevated: "shadow-md",
        ghost:    "border-0 shadow-none",
        // Apple-style "frosted" card for dark mode overlays
        frosted:  "backdrop-blur-xl bg-surface-overlay border border-border-default shadow-lg",
      },
      interactive: {
        true:  "cursor-pointer hover:shadow-md hover:-translate-y-px active:translate-y-0",
        false: "",
      },
    },
    defaultVariants: {
      variant:     "default",
      interactive: false,
    },
  }
);

interface CardProps extends VariantProps<typeof cardVariants> {
  children: ReactNode;
  className?: string;
}

export function Card({ variant, interactive, children, className }: CardProps) {
  return (
    <div className={cn(cardVariants({ variant, interactive }), className)}>
      {children}
    </div>
  );
}

export function CardHeader({ children, className }: { children: ReactNode; className?: string }) {
  return <div className={cn("px-6 pt-6 pb-4", className)}>{children}</div>;
}

export function CardBody({ children, className }: { children: ReactNode; className?: string }) {
  return <div className={cn("px-6 pb-6", className)}>{children}</div>;
}

// ── Badge ─────────────────────────────────────────────────────────────────────

const badgeVariants = cva(
  "inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium",
  {
    variants: {
      variant: {
        default:  "bg-surface-tertiary text-text-secondary",
        accent:   "bg-blue-50 text-brand-accent dark:bg-blue-950 dark:text-blue-300",
        success:  "bg-success-bg text-success",
        warning:  "bg-warning-bg text-warning",
        error:    "bg-error-bg text-error",
        ai:       "bg-ai-bg text-ai",
      },
    },
    defaultVariants: { variant: "default" },
  }
);

interface BadgeProps extends VariantProps<typeof badgeVariants> {
  children: ReactNode;
  className?: string;
}

export function Badge({ variant, children, className }: BadgeProps) {
  return <span className={cn(badgeVariants({ variant }), className)}>{children}</span>;
}

// ── Typography ────────────────────────────────────────────────────────────────

// Hero headline — Apple-scale, tight tracking
export function HeroHeadline({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <h1
      className={cn(
        "font-display font-bold text-text-primary",
        "text-5xl leading-none tracking-tighter",   // 80px, -0.05em
        "md:text-6xl",                              // 96px on wide
        className
      )}
    >
      {children}
    </h1>
  );
}

// Section headline
export function SectionHeadline({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <h2
      className={cn(
        "font-display font-bold text-text-primary",
        "text-3xl leading-snug tracking-snug",      // 40px, -0.03em
        className
      )}
    >
      {children}
    </h2>
  );
}

// Body copy — Apple 17px standard
export function BodyText({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <p
      className={cn(
        "font-sans text-base leading-relaxed text-text-secondary",
        "max-w-narrow",   // 680px — Apple body copy max-width
        className
      )}
    >
      {children}
    </p>
  );
}

// ── Divider ───────────────────────────────────────────────────────────────────

export function Divider({ className }: { className?: string }) {
  return <hr className={cn("border-0 border-t border-border-default", className)} />;
}

// ── Token display (Engineering-specific) ─────────────────────────────────────

// Shows a numeric parameter value with unit — used in FEM/CFD/simulation panels
export function ParameterValue({
  label,
  value,
  unit,
  variant = "default",
}: {
  label: string;
  value: number | string;
  unit?: string;
  variant?: "default" | "warning" | "error" | "ai";
}) {
  const valueColors = {
    default: "text-text-primary",
    warning: "text-warning",
    error:   "text-error",
    ai:      "text-ai",
  };
  return (
    <div className="flex items-baseline justify-between gap-2 py-1">
      <span className="text-sm text-text-secondary truncate">{label}</span>
      <span className={cn("font-mono text-sm tabular-nums", valueColors[variant])}>
        {value}
        {unit && <span className="text-text-tertiary ml-1 text-xs">{unit}</span>}
      </span>
    </div>
  );
}
