/**
 * ODE Tailwind Config — Apple-inspired Design System
 * Generated by: Figma → Claude Code workflow
 * Source of truth: design/design-tokens.css
 *
 * Usage: copy to project root, import in CSS with @config
 */

import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      // ── Colors ──────────────────────────────────────────────
      colors: {
        brand: {
          midnight: "#0A2540",
          accent:   "#0071E3",
          "accent-hover":   "#0077ED",
          "accent-pressed": "#006EDB",
        },
        // Semantic surface tokens — reference CSS vars in components
        surface: {
          primary:   "var(--color-bg-primary)",
          secondary: "var(--color-bg-secondary)",
          tertiary:  "var(--color-bg-tertiary)",
          overlay:   "var(--color-bg-overlay)",
        },
        text: {
          primary:   "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary:  "var(--color-text-tertiary)",
          disabled:  "var(--color-text-disabled)",
          link:      "var(--color-text-link)",
        },
        border: {
          default: "var(--color-border-default)",
          strong:  "var(--color-border-strong)",
          focus:   "var(--color-border-focus)",
        },
        // Semantic states
        success: { DEFAULT: "#34C759", bg: "#F0FFF4" },
        warning: { DEFAULT: "#FF9F0A", bg: "#FFFBEB" },
        error:   { DEFAULT: "#FF3B30", bg: "#FFF5F5" },
        ai:      { DEFAULT: "#5E5CE6", bg: "#F5F5FF" },
      },

      // ── Typography ───────────────────────────────────────────
      fontFamily: {
        display: [
          "-apple-system", "BlinkMacSystemFont", "SF Pro Display",
          "Helvetica Neue", "Arial", "sans-serif",
        ],
        sans: [
          "-apple-system", "BlinkMacSystemFont", "SF Pro Text",
          "Helvetica Neue", "Arial", "sans-serif",
        ],
        mono: [
          "SF Mono", "JetBrains Mono", "Fira Code",
          "Menlo", "Monaco", "Consolas", "monospace",
        ],
      },

      fontSize: {
        xs:   ["11px", { lineHeight: "1.5",  letterSpacing: "0.01em"  }],
        sm:   ["13px", { lineHeight: "1.5",  letterSpacing: "0"       }],
        base: ["17px", { lineHeight: "1.6",  letterSpacing: "0"       }],
        lg:   ["19px", { lineHeight: "1.5",  letterSpacing: "0"       }],
        xl:   ["21px", { lineHeight: "1.4",  letterSpacing: "-0.01em" }],
        "2xl":["28px", { lineHeight: "1.3",  letterSpacing: "-0.02em" }],
        "3xl":["40px", { lineHeight: "1.1",  letterSpacing: "-0.03em" }],
        "4xl":["56px", { lineHeight: "1.05", letterSpacing: "-0.04em" }],
        "5xl":["80px", { lineHeight: "1.0",  letterSpacing: "-0.05em" }],
        "6xl":["96px", { lineHeight: "0.95", letterSpacing: "-0.06em" }],
      },

      // ── Spacing — 8pt grid ───────────────────────────────────
      spacing: {
        "0":  "0px",
        "1":  "4px",
        "2":  "8px",
        "3":  "12px",
        "4":  "16px",
        "5":  "20px",
        "6":  "24px",
        "8":  "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
        "32": "128px",
        "40": "160px",
      },

      // ── Border Radius ────────────────────────────────────────
      borderRadius: {
        sm:   "6px",
        md:   "10px",
        lg:   "16px",
        xl:   "20px",
        "2xl":"28px",
        full: "9999px",
      },

      // ── Shadows (Apple — extremely subtle) ───────────────────
      boxShadow: {
        xs:  "0 1px 2px rgba(0,0,0,0.04)",
        sm:  "0 2px 8px rgba(0,0,0,0.06)",
        md:  "0 4px 16px rgba(0,0,0,0.08)",
        lg:  "0 8px 32px rgba(0,0,0,0.10)",
        xl:  "0 16px 48px rgba(0,0,0,0.12)",
        // Dark mode shadows in dark: variant
      },

      // ── Max Widths ───────────────────────────────────────────
      maxWidth: {
        content: "1280px",
        narrow:  "680px",
        hero:    "1440px",
      },

      // ── Transitions ──────────────────────────────────────────
      transitionDuration: {
        fast:   "200ms",
        normal: "300ms",
        slow:   "500ms",
        spring: "600ms",
      },
      transitionTimingFunction: {
        "ease-out":    "cubic-bezier(0.0, 0.0, 0.2, 1.0)",
        "ease-in-out": "cubic-bezier(0.4, 0.0, 0.2, 1.0)",
        "spring":      "cubic-bezier(0.16, 1.0, 0.30, 1.0)",
      },

      // ── Layout ───────────────────────────────────────────────
      width: {
        sidebar:           "240px",
        "sidebar-collapsed":"48px",
        "panel-right":     "300px",
      },
      height: {
        topbar:       "52px",
        "panel-bottom": "200px",
      },
    },
  },
  plugins: [],
};

export default config;
